### ISSUE TITLE
New Architecture Support 

### ISSUE THREAD

**Issue by peraronsson** [wouterds/react-native-tv-example#2]
Currently, the package `react-native-safe-area-context` seems to be blocking the use of RN "new architeture" in this project.

> This library currently has experimental support for the new react-native architecture. Note that there will be breaking changes and only the latest version of react-native will be supported. **You will need to be on 4.4.0 and react-native 0.70+.**

_Ref: https://github.com/th3rdwave/react-native-safe-area-context#new-architecture-support_

However, the latest version of react-native-tvos is using `react-native@0.69.8`.

_Ref: https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.69.6/package.json_

Just thought I'd share this observation here, in case anyone considers trying RN "new architeture" in this project.

**Comment by wouterds** [comment]
Thanks for letting me now, I'm gonna update this project to the latest version and get rid of a few hacks and workarounds that now work out of the box using TVFocusGuideView soon and will have a look at it then.

**Comment by wouterds** [comment]
At this moment the latest available version of react-native-tvos is 0.69.8-1. Whenever we 0.70+ gets released I'll look into it.
